export const COLLECTIONS = {
  USERS: 'users',
  TASKS: 'tasks',
  SUBTASKS: 'subtasks',
  COMMENTS: 'comments',
  NOTIFICATIONS: 'notifications',
  AUDIT_LOGS: 'audit_logs',
  SUPPLY_MOVEMENTS: 'supply_movements',
  COLD_STORAGE: 'cold_storage',
  RAW_MATERIAL: 'raw_material',
  BARRELS: 'barrels',
  BARREL_MOVEMENTS: 'barrel_movements',
  THIRD_PARTY_PROCESSING: 'third_party_processing',
  PROCESS_ITEMS: 'process_items',
  WAREHOUSES: 'warehouses',
  SETTINGS: 'settings',
  AGRI_RAW_MATERIAL: 'agri_raw_material',
  PURCHASE_ORDERS: 'purchase_orders',
};
